language: node_js

node_js:
  - lts/*

cache: yarn

deploy:
  - provider: npm
    script: yarn build
    email: michael19920327@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    script: yarn deploy
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      tags: true
