language: node_js

node_js:
  - lts/*

cache: yarn

before_deploy:
  - if ! [ $BEFORE_DEPLOY_RUN ]; then
    BEFORE_DEPLOY_RUN=true
    yarn build
    else
    yarn deploy
    fi

deploy:
  - provider: npm
    email: michael19920327@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true

  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    local_dir: dist
    on:
      tags: true
