language: node_js

node_js:
  - lts/*

cache: yarn

jobs:
  include:
    - stage: Test
      script: yarn test

    - stage: NPM publish
      before_deploy: yarn build
      deploy:
        provider: npm
        email: michael19920327@gmail.com
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true

    - stage: Demo deploy
      before_deploy: yarn deploy
      deploy:
        provider: pages
        script: yarn deploy
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          tags: true
