language: node_js

node_js:
  - lts/*

cache: yarn

before_deploy:
  - yarn build

deploy:
  provider: npm
  email: michael19920327@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
